from _Functions.F_statement_generator_v3 import statement_generator


# requires F_statement_generator

# displays instructions
def instructions():
    statement_generator("Here are the rules", "-", 3)
    print('''
- ...
- ...
- ...
- ...
- ...  
    ''')
    